version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: nehalwandhare/backend:latest
    container_name: backend-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: studentapp
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: nehalwandhare/frontend:latest
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentapp
    ports:
      - "3306:3306"
