name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # 🔥 manual trigger added

jobs:

  # 🔹 BUILD JOB
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Images
      run: docker compose build

    - name: List Docker Images
      run: docker images

  # 🔹 SNYK JOB
  snyk:
    runs-on: ubuntu-latest
    needs: build   # depends on build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Images (again for this job)
      run: docker compose build

    - name: Install Snyk
      run: npm install -g snyk

    - name: Snyk Container Scan
      run: |
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk container test nehalwandhare/backend:latest --file=Backend/Dockerfile
