name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Images
      run: docker compose build

    # 🔍 Debug (very useful)
    - name: List Docker Images
      run: docker images

    - name: Install Snyk
      run: npm install -g snyk

    - name: Snyk Container Scan (Detailed)
      run: |
         snyk auth ${{ secrets.SNYK_TOKEN }}
         snyk container test nehalwandhare/backend:latest --file=Dockerfile
